### ISSUE TITLE
Bower install failing with 404 error

### ISSUE THREAD

**Issue by pdsmith1223** [lissy93/twitter-sentiment-visualisation#14]
While trying to install the dependencies bower is failing on various packages with a 404 error:

bower validate      0.4.18 against https://github.com/masayuki0812/c3.git#~0.4.10
bower EHTTP         Status code of 404

bower validate      0.1.9 against https://github.com/ArtemFitiskin/jquery-autocompleter.git#~0.1.9
bower EHTTP         Status code of 404

Tried to diagnose this manually but haven't found any inconsistencies

**Comment by lissy93** [comment]
![image](https://user-images.githubusercontent.com/1862727/30635164-7f9affc0-9de9-11e7-8cc9-8b2a7f09b2ba.png)

Hey @pdsmith1223 

You should be able to see from your console output, which dependency is causing it to fail- in this case it is Socket.io (with a 404), looks like they've just updated their file paths, no big deal. 

So to fix, just run  `bower install socket.io`. 
I've just pushed the fix (see [this commit](https://github.com/Lissy93/twitter-sentiment-visualisation/commit/e5982a989251b52d66800c6a68d977b545db4456)), so if you pull from dev, your problem should be solved 😃 

Hope that helps,
Alicia

**Comment by pdsmith1223** [comment]
@Lissy93 - Thanks! One quick question (if you don't mind answering). I'm trying to deploy this app on either AWS or Heroku and both are failing due to dependencies. Would you happen to know why?

**Comment by lissy93** [comment]
What's the error message?
