### ISSUE TITLE
Server automatically terminates when Entity Extraction Link is clicked [Error Log attached]

### ISSUE THREAD

**Issue by kartikpuri196** [lissy93/twitter-sentiment-visualisation#23]
[2018-04-13T06_03_15_117Z-debug.log](https://github.com/Lissy93/twitter-sentiment-visualisation/files/1906066/2018-04-13T06_03_15_117Z-debug.log)

**Comment by lissy93** [comment]
Thanks for raising, and for attaching the error log, but I'm unable to recreate this. And it seems to be working fine in the live environment too. 
Try updating your dependencies. If the issue still persists reply on here with some more info (like browser, OS, node version...)

**Comment by lissy93** [comment]
Closing due to no response, and not able to reproduce this issue in any environment
