### ISSUE TITLE
#error After running NPM RUN CONFIG

### ISSUE THREAD

**Issue by nithin7vnnr** [lissy93/twitter-sentiment-visualisation#24]
After running NPM RUN CONFIG, I get the following error (note I have the latest nodejs and NPM):

nithin@nithin-VirtualBox:~/twitter-sentiment-visualisation$ sudo npm run config

    twitter-sentiment-visualisation@1.5.0 config /home/nithin/twitter-sentiment-visualisation
    gulp generate-config && start notepad 'config\src\keys.coffee'

[11:39:20] Using gulpfile ~/twitter-sentiment-visualisation/gulpfile.js
[11:39:20] Starting 'generate-config'...
[11:39:20] Finished 'generate-config' after 354 μs
start: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! twitter-sentiment-visualisation@1.5.0 config: gulp generate-config && start notepad 'config\src\keys.coffee'
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the twitter-sentiment-visualisation@1.5.0 config script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! /home/nithin/.npm/_logs/2018-04-29T06_09_20_518Z-debug.log

**Comment by lissy93** [comment]
From that stack trace, looks like everything generated just fine. All that happened is that it couldn't open your text editor (because you're on Unix). Feel free to send a pull request containing your fix.

**Comment by lissy93** [comment]
Also, for future reference when raising an issue (@nithin7vnnr):
 - Include system details, and exact software versions (Node, npm, OS, etc..)
 - Include the exact command you ran (aka not `NPM RUN CONFIG`, because that would have thrown a command not found error!). And include your debug log
 - Don't copy+ paste the same issue in multiple different places, it just gets confusing for trying to keep track
 - Run the tests first, as they often give you a more helpful output
 - Tell us what you've tried so far to debug and fix it

**Comment by nithin7vnnr** [comment]
Thanks for the reply, one question In which environment I should run all
those comands
Please let me know

Thank you

**Comment by lissy93** [comment]
Should work fine in any dev environment. I have the prod demo working on a CentOS server but did the development for this app across Windows and Debian. Are you using a VM?

If you come across any issues in a particular environment, debug then raise it as an issue with all the details and I can look into it 😃

**Comment by nithin7vnnr** [comment]
Thanks once again, I will mention all these things

OS : Ubuntu 16
node js : ver 8
mango db: ver  3.2

please suggest me in which environment I should use to run the project and
if i am wrong please don't mind.

Thank you.

**Comment by nithin7vnnr** [comment]
thank you, Yes I am using VM in that I deployed Ubuntu 16. I attached the
debug log please go through it and help me out.

Thank you.
