### ISSUE TITLE
Broken Dependencies

### ISSUE THREAD

**Issue by srinathvijay** [lissy93/twitter-sentiment-visualisation#3]
Hi ,
I followed the steps given under running locally. But "bower install" in step 3 generates an error. Its because some of the dependencies return **"404:Not found"** status. They are 
```
**"markerclusterer_compiled": "https://raw.githubusercontent.com/googlemaps/js-marker-clusterer/gh-pages/src/markerclusterer_compiled.js",**
**"socket.io": "https://raw.githubusercontent.com/socketio/socket.io-client/master/socket.io.js",**
**"d3-word-cloud": "https://jardindesconnaissances.googlecode.com/svn-history/r82/trunk/public/js/d3.layout.cloud.js",**
```

Also when I "npm run build" it generates several errors in the various coffee files.Kindly look into it
P.S : I am working in Ubuntu 14.04

**Comment by lissy93** [comment]
Create these as separate issues if they are going to be worked on independently. 
For the first, a quick Google search brought up the following: https://github.com/googlemaps/js-marker-clusterer/issues/74  Its simply that magnetometer has  changed location, so the `bower.json` just needs updating, it's a quick fix :-) I'd suggest doing it as a pull request of the main branch, and then I'll merge your change in once tested

**Comment by srinathvijay** [comment]
Thank u mam. It works fine :)

**Comment by srinathvijay** [comment]
Thank u mam. It works fine :)
