### ISSUE TITLE
d3.tip is not a function error

### ISSUE THREAD

**Issue by tanmaya-git** [lissy93/twitter-sentiment-visualisation#30]
hexagons-module.js:32 Uncaught TypeError: Cannot read property 'attr' of undefined
    at renderHexChart (hexagons-module.js:32)
    at hexagons-module.js:114
    at hexagons-module.js:152

**Comment by lissy93** [comment]
Ah, that's a bower issue. Bower is basically dead, so you need to install [tippy ](https://atomiks.github.io/tippyjs/) yourself, it's easy, just follow the steps in the documentation. 
Hope that helps 😃 
Alicia 🚀

**Comment by tanmaya-git** [comment]
I installed tippy-
npm i tippy.js
But still I am getting the same error.

<img width="1274" alt="screen shot 2019-02-05 at 2 10 48 pm" src="https://user-images.githubusercontent.com/43648623/52307575-e1dca600-294f-11e9-8eaf-3217caeff2bd.png">

**Comment by lissy93** [comment]
Yeah, looks like you've not configured it.  Use examples from online documentation, or elsewhere in the app if your unsure how.

You'll also need this referenced, if you've not got it already: 
`https://cdnjs.cloudflare.com/ajax/libs/d3-tip/0.7.1/d3-tip.min.js`
