### ISSUE TITLE
havenondemand.com API

### ISSUE THREAD

**Issue by kitsune0n** [lissy93/twitter-sentiment-visualisation#37]
what u use as alternative? i see demo is working

**Comment by lissy93** [comment]
Yeah Haven on Demand has been depricated, I wrote my own module which can do simple Sentiment Analysis ofline (see [sentiment-analysis](https://www.npmjs.com/package/sentiment-analysis)), but for more advanced stuff I recomend taking a look at Google Cloud, AWS and Azure's NLU offerings, all of them let you get started for free, and have good results. 

Hope that helps :)

**Comment by kitsune0n** [comment]
Thx u 🙂 i understand, is this project use it? And working without haven on demand ?

**Comment by lissy93** [comment]
It did used to use it, but not any more since Haven no longer works, now I use my own sentiment-analysis algorithm :)
