### ISSUE TITLE
Entity API

### ISSUE THREAD

**Issue by ianmyles** [lissy93/twitter-sentiment-visualisation#5]
Hi I seem to have the bulk of the project working locally however I'm getting an error on the following line: twitter-sentiment-visualisation/routes/entity-api.js:21
    ref = Object.keys(data);
It looks like my configuration for the API may not be correct. Currently I have:

exports.hp = {
    apiKey: 'XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXX'
  };

Thanks

**Comment by lissy93** [comment]
Yes, as per readme, you will need to populate this file with your API keys. `xxxxxxx` is just the placeholder.

You HP API key will look something like this: `bc3d211e-4212-417b-ae54-04823565c76g`
(this is a sample one, so won't work!)

You can sighn up for your key here: https://www.havenondemand.com/login.html?signUp=true
