### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by akashdave11** [lissy93/twitter-sentiment-visualisation#6]
Hi i am getting an error when i build/run 
`npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! twitter-sentiment-visualisation@0.0.1 build: `gulp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the twitter-sentiment-visualisation@0.0.1 build script 'gulp build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the twitter-sentiment-visualisation package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs twitter-sentiment-visualisation
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls twitter-sentiment-visualisation
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\New folder (2)\Wiki article\twitter-sentiment-visualisation\npm-debug.log

C:\New folder (2)\Wiki article\twitter-sentiment-visualisation>npm bugs twitter-sentiment-visualisation
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "bugs" "twitter-sentiment-visualisation"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/twitter-sentiment-visualisation
npm ERR! 404
npm ERR! 404  'twitter-sentiment-visualisation' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\New folder (2)\Wiki article\twitter-sentiment-visualisation\npm-debug.log
`

**Comment by lissy93** [comment]
I'm having trouble recreating this issue. Can you supply information about your system (Windows/ Linux, version of Node, NPM...)?

**Comment by akashdave11** [comment]
Windows 10 (64 bit)
npm version : 3.10.10
node version : 6.10.2

Also i ran the command 'npm install' a second time and got the following error

`MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the syst
em path if it is installed elsewhere.  [C:\New folder (2)\Wiki article\twitter-sentiment-visualisation\node_modules\weak\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\New folder (2)\Wiki article\twitter-sentiment-visualisation\node_modules\weak
gyp ERR! node -v v6.10.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok`

**Comment by lissy93** [comment]
okay, thanks @akashdave11 for the info. I'm closing this as both issues are to do with your system, not with the project.

**First issue** is because you have missing dependencies- your using an old version of npm too, first update your version of npm (`npm i -g npm`), then run `npm install`  

**Second issue** will be resolved if you install the .NET framework 2.0 SDK, or follow the instructions in the error message.

Hope that helps

**Comment by akashdave11** [comment]
So i did as you said i.e updated my npm.
For the second one i had alot of issues ended up running "**npm install --global --production windows-build-tools**" and now npm install doesnt give the .Net issue just 2 warnings.

However on running the npm run build command again a different error appeared

`loading.coffee
    line 18  Line contains a trailing semicolon
    line 19  Line contains a trailing semicolon
    line 22  Line exceeds maximum allowed length  Length is 81, max is 80

 3 errors


break-down.coffee
    line 57  Line contains inconsistent indentation  Expected 2 got 4
    line 79  Line contains inconsistent indentation  Expected 2 got 4

 2 errors


client-side-source\scripts\analytics.js
  line 1  col 27  ['GoogleAnalyticsObject'] is better written in dot notation.
  line 2  col 36  Missing semicolon.
  line 2  col 56  Expected an assignment or function call and instead saw an expression.
  line 3  col 30  Expected an assignment or function call and instead saw an expression.
  line 3  col 80  Missing semicolon.

  ‼  5 warnings

[14:39:47] Size analytics.js : 378 B
[14:39:47] Size loading.js : 872 B
[14:39:47] Size Tweet.js : 533 B
[14:39:47] Size async-tweets.js : 705 B

server-side-source\utils\fetch-sentiment-tweets.js
  line 25  col 20  Did you mean to return a conditional instead of an assignment?

  ‼  1 warning

[14:39:47] Size fetch-sentiment-tweets.js : 999 B
[14:39:47] Size app-config.js : 769 B
[14:39:47] Size keys.js : 263 B
[14:39:47] Size about.js : 176 B

server-side-source\routes\break-down.js
  line 39  col 21  Did you mean to return a conditional instead of an assignment?

  ‼  1 warning

[14:39:47] Size break-down.js : 2.65 kB
[14:39:47] Size db-api.js : 240 B

server-side-source\api-routes\entity-api.js
  line 15  col 23  Did you mean to return a conditional instead of an assignment?
  line 30  col 21  Did you mean to return a conditional instead of an assignment?

  ‼  2 warnings

[14:39:47] Size entity-api.js : 789 B

client-side-source\scripts\visualisations\break-down.js
  line 40  col 36  Use '!==' to compare with 'null'.
  line 80  col 31  Did you mean to return a conditional instead of an assignment?

  ‼  2 warnings

[14:39:47] Size break-down.js : 1.78 kB

client-side-source\scripts\visualisations\comparer.js
  line 42  col 29  Did you mean to return a conditional instead of an assignment?

  ‼  1 warning

[14:39:47] Size comparer.js : 1.08 kB

page-controls-module.coffee
    line 21  Line exceeds maximum allowed length  Length is 81, max is 80

 1 error


client-side-source\scripts\page-controls-module.js
  line 14  col 31  Did you mean to return a conditional instead of an assignment?
  line 40  col 21  Did you mean to return a conditional instead of an assignment?
  line 42  col 21  Did you mean to return a conditional instead of an assignment?
  line 48  col 22  Did you mean to return a conditional instead of an assignment?

  ‼  4 warnings

[14:39:48] Size page-controls-module.js : 859 B
[14:39:48] Size comparison-for-search.js : 679 B

server-side-source\utils\format-for-keyword-vis.js
  line 25  col 20  Use '===' to compare with 'null'.
  line 34  col 30  Don't make functions within a loop.
  line 90  col 26  Did you mean to return a conditional instead of an assignment?

  ‼  3 warnings

[14:39:48] Size format-for-keyword-vis.js : 3.17 kB
[14:39:48] Size sample-keys.js : 262 B

server-side-source\routes\comparer.js
  line 18  col 30  Don't make functions within a loop.
  line 22  col 53  Don't make functions within a loop.

  ‼  2 warnings

[14:39:48] Size comparer.js : 1.69 kB

server-side-source\api-routes\tone-api.js
  line 32  col 25  Did you mean to return a conditional instead of an assignment?
  line 45  col 30  Use '!==' to compare with 'null'.
  line 57  col 24  Use '===' to compare with 'null'.

  ‼  3 warnings

[14:39:48] Size tone-api.js : 1.28 kB

client-side-source\scripts\visualisations\comparison.js
  line 26   col 102  Use '!==' to compare with 'null'.
  line 156  col 59   Did you mean to return a conditional instead of an assignment?

  ‼  2 warnings

[14:39:49] Size comparison.js : 4.98 kB

server-side-source\utils\format-tweets-for-map.js
  line 36  col 34  Use '===' to compare with 'null'.
  line 66  col 14  Don't make functions within a loop.
  line 82  col 36  Use '!==' to compare with 'null'.
  line 85  col 43  Use '===' to compare with 'null'.
  line 88  col 43  Use '===' to compare with 'null'.

  ‼  5 warnings

[14:39:49] Size format-tweets-for-map.js : 3.25 kB

server-side-source\routes\entity-extraction.js
  line 29  col 21  Did you mean to return a conditional instead of an assignment?

  ‼  1 warning

[14:39:49] Size entity-extraction.js : 2.50 kB

server-side-source\api-routes\trending-api.js
  line 49  col 32  Use '===' to compare with 'null'.
  line 92  col 30  Use '===' to compare with 'null'.

  ‼  2 warnings

[14:39:49] Size trending-api.js : 2.13 kB

entity-extraction.coffee
    line 32  Line contains inconsistent indentation  Expected 2 got 4
    line 34  Line contains inconsistent indentation  Expected 2 got 0

 2 errors

[14:39:49] Finished 'browserify' after 4.03 s

client-side-source\scripts\visualisations\entity-extraction.js
  line 42  col 29  Did you mean to return a conditional instead of an assignment?
  line 76  col 21  Did you mean to return a conditional instead of an assignment?
  line 94  col 31  Did you mean to return a conditional instead of an assignment?

  ‼  3 warnings

[14:39:49] Size entity-extraction.js : 2.77 kB
[14:39:49] Size get-complete-tweets.js : 1.75 kB
[14:39:49] Size globe.js : 1.08 kB

entity-summary.coffee
    line 8   Line exceeds maximum allowed length  Length is 88, max is 80
    line 25  Line exceeds maximum allowed length  Length is 102, max is 80

 2 errors


make-click-words.coffee
    line 12  Line exceeds maximum allowed length  Length is 81, max is 80

 1 error


client-side-source\scripts\visualisations\entity-summary.js
  line 11  col 15  Use '!==' to compare with 'null'.

  ‼  1 warning

[14:39:50] Size entity-summary.js : 1.45 kB
[14:39:50] Size make-click-words.js : 551 B
[14:39:50] Size hexagons.js : 908 B

make-summary-sentences.coffee
    line 70  Line exceeds maximum allowed length  Length is 81, max is 80

 1 error

[14:39:50] Size gauge-module.js : 601 B

server-side-source\utils\make-summary-sentences.js
  line 9    col 36  Use '!==' to compare with 'null'.
  line 102  col 31  Use '!==' to compare with 'null'.

  ‼  2 warnings

[14:39:50] Size make-summary-sentences.js : 3.45 kB
[14:39:50] Size index.js : 483 B

hexagons-module.coffee
    line 106  Line contains a trailing semicolon

 1 error


make-timeline-data.coffee
    line 28  Line exceeds maximum allowed length  Length is 81, max is 80
    line 30  Line exceeds maximum allowed length  Length is 81, max is 80

 2 errors


client-side-source\scripts\visualisations\hexagons-module.js
  line 92  col 16  Did you mean to return a conditional instead of an assignment?
  line 96  col 16  Did you mean to return a conditional instead of an assignment?

  ‼  2 warnings

[14:39:51] Size hexagons-module.js : 3.54 kB
[14:39:51] Size make-timeline-data.js : 2.62 kB
[14:39:51] Size map.js : 1.07 kB
[14:39:52] Size home-page.js : 1.09 kB

server-side-source\utils\stream-handler.js
  line 38  col 34  Use '!==' to compare with 'null'.
  line 41  col 41  Use '===' to compare with 'null'.
  line 44  col 41  Use '===' to compare with 'null'.

  ‼  3 warnings

[14:39:52] Size stream-handler.js : 2.40 kB
[14:39:52] Size now.js : 202 B
[14:39:52] Size all.min.css : 4.61 kB
C:\New folder (2)\Wiki article\twitter-sentiment-visualisation\node_modules\bower\node_modules\q\q.js:126
                    throw e;
                    ^

Error: could not resolve dependency d3 : bower returns the module as known but not found (did you forget to run bower install ?) (C:\New folder (2)\Wiki article\twitter-sentiment-visualisation\client-side-source\scripts\visualisations\scatter-words-main.coffee) while parsing file: C:\New folder (2)\Wiki article\twitter-sentiment-visualisation\client-side-source\scripts\visualisations\scatter-words-main.coffee
  at next (C:\New folder (2)\Wiki article\twitter-sentiment-visualisation\node_modules\debowerify\index.js:36:26)
  at Logger.<anonymous> (C:\New folder (2)\Wiki article\twitter-sentiment-visualisation\node_modules\debowerify\index.js:26:11)
  at emitOne (events.js:96:13)
  at Logger.emit (events.js:188:7)
  at Logger.emit (C:\New folder (2)\Wiki article\twitter-sentiment-visualisation\node_modules\bower-logger\lib\Logger.js:29:39)
  at C:\New folder (2)\Wiki article\twitter-sentiment-visualisation\node_modules\bower\lib\commands\index.js:38:25
  at _fulfilled (C:\New folder (2)\Wiki article\twitter-sentiment-visualisation\node_modules\bower\node_modules\q\q.js:787:54)
  at self.promiseDispatch.done (C:\New folder (2)\Wiki article\twitter-sentiment-visualisation\node_modules\bower\node_modules\q\q.js:816:30)
  at Promise.promise.promiseDispatch (C:\New folder (2)\Wiki article\twitter-sentiment-visualisation\node_modules\bower\node_modules\q\q.js:749:13)
  at C:\New folder (2)\Wiki article\twitter-sentiment-visualisation\node_modules\bower\node_modules\q\q.js:557:44
  at flush (C:\New folder (2)\Wiki article\twitter-sentiment-visualisation\node_modules\bower\node_modules\q\q.js:108:17)
  at _combinedTickCallback (internal/process/next_tick.js:73:7)
  at process._tickDomainCallback (internal/process/next_tick.js:128:9)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! twitter-sentiment-visualisation@0.0.1 build: `gulp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the twitter-sentiment-visualisation@0.0.1 build script 'gulp build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the twitter-sentiment-visualisation package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs twitter-sentiment-visualisation
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls twitter-sentiment-visualisation
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\atul dave\AppData\Roaming\npm-cache\_logs\2017-04-20T09_09_53_035Z-debug.log`

Would really appreciate if you could look into it
